basePath: /v2
info:
  contact:
    email: support@swagger.io2
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample swagger doc.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Gin Swagger Api
  version: "1.0"
paths: {}
swagger: "2.0"
